"""
Evaluating the quality of synthetic transactions generated by CTGAN.

Three levels of verification:
1. Statistical similarity of distributions (KS test for each feature).
2. Comparison of correlation matrices (real fraud vs. synthetic fraud).
3. TSTR (Train on Synthetic, Test on Real) - we train the classifier
   ONLY on synthetic data to distinguish fraud from normal transactions and then test it
   on real data. If the metrics are reasonable, then the synthetic data
   truly carries a useful signal, rather than just noise.
"""
import json
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from scipy.stats import ks_2samp
import xgboost as xgb
from sklearn.metrics import average_precision_score, roc_auc_score, precision_recall_fscore_support

from config import (
    TARGET_COL, TRAIN_PROCESSED_PATH, TEST_PROCESSED_PATH,
    TOP_K_FEATURES_PATH, SYNTHETIC_FRAUD_PATH, PLOTS_DIR, RANDOM_STATE,
)

sns.set_theme(style="whitegrid")


def statistical_similarity(real_fraud: pd.DataFrame, synthetic_fraud: pd.DataFrame, features: list):
    """KS test for each characteristic: the closer the statistic is to 0 and the higher the p-value, the better."""
    rows = []
    for col in features:
        stat, pvalue = ks_2samp(real_fraud[col], synthetic_fraud[col])
        rows.append(dict(feature=col, ks_statistic=stat, p_value=pvalue))
    result = pd.DataFrame(rows).sort_values("ks_statistic", ascending=False)
    print("\n=== KS test: real fraud vs synthetic fraud ===")
    print("(ks_statistic closer to 0 = distributions more similar)")
    print(result.to_string(index=False))
    return result


def plot_feature_distributions(real_fraud, synthetic_fraud, features, n_show=6):
    """Plot histograms for several most important features: real vs synthetic."""
    features_to_plot = features[:n_show]
    fig, axes = plt.subplots(2, 3, figsize=(15, 8))
    axes = axes.flatten()

    for i, col in enumerate(features_to_plot):
        ax = axes[i]
        sns.kdeplot(real_fraud[col], label="Real Fraud", ax=ax, fill=True, alpha=0.4)
        sns.kdeplot(synthetic_fraud[col], label="Synthetic Fraud", ax=ax, fill=True, alpha=0.4)
        ax.set_title(col)
        ax.legend(fontsize=8)

    fig.tight_layout()
    fig.savefig(PLOTS_DIR / "05_synthetic_vs_real_distributions.png", dpi=150)
    plt.close(fig)
    print(f"[eval] Graphs of distributions saved to {PLOTS_DIR / '05_synthetic_vs_real_distributions.png'}")


def plot_correlation_comparison(real_fraud, synthetic_fraud, features):
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    sns.heatmap(real_fraud[features].corr(), ax=axes[0], cmap="coolwarm", center=0, cbar=False)
    axes[0].set_title("Correlations: Real Fraud")

    sns.heatmap(synthetic_fraud[features].corr(), ax=axes[1], cmap="coolwarm", center=0, cbar=False)
    axes[1].set_title("Correlations: Synthetic Fraud")

    fig.tight_layout()
    fig.savefig(PLOTS_DIR / "06_correlation_comparison.png", dpi=150)
    plt.close(fig)
    print(f"[eval] Comparison of correlations saved to {PLOTS_DIR / '06_correlation_comparison.png'}")


def tstr_evaluation(train_df, test_df, synthetic_fraud, features):
    """Train on Synthetic, Test on Real.

        We train the classifier on synthetic fraud data + real normal
        transactions (otherwise, the classifier would have nothing to learn from to distinguish between classes),
        and test it on a real test set."""
    real_normal = train_df.loc[train_df[TARGET_COL] == 0, features + [TARGET_COL]]

    tstr_train = pd.concat([
        real_normal,
        synthetic_fraud[features + [TARGET_COL]],
    ], ignore_index=True).sample(frac=1, random_state=RANDOM_STATE)

    X_train, y_train = tstr_train[features], tstr_train[TARGET_COL]
    X_test, y_test = test_df[features], test_df[TARGET_COL]

    model = xgb.XGBClassifier(
        n_estimators=300, max_depth=6, learning_rate=0.05,
        eval_metric="aucpr", random_state=RANDOM_STATE, n_jobs=-1,
    )
    model.fit(X_train, y_train)

    proba = model.predict_proba(X_test)[:, 1]
    preds = (proba >= 0.5).astype(int)

    pr_auc = average_precision_score(y_test, proba)
    roc_auc = roc_auc_score(y_test, proba)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_test, preds, average="binary", zero_division=0
    )

    print("\n=== TSTR: training on synthetic, testing on real data ===")
    print(f"PR-AUC:    {pr_auc:.4f}")
    print(f"ROC-AUC:   {roc_auc:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1:        {f1:.4f}")

    return dict(pr_auc=pr_auc, roc_auc=roc_auc, precision=precision, recall=recall, f1=f1)


def main():
    train_df = pd.read_parquet(TRAIN_PROCESSED_PATH)
    test_df = pd.read_parquet(TEST_PROCESSED_PATH)
    synthetic_fraud = pd.read_parquet(SYNTHETIC_FRAUD_PATH)

    with open(TOP_K_FEATURES_PATH) as f:
        features = json.load(f)

    real_fraud = train_df.loc[train_df[TARGET_COL] == 1, features]
    synthetic_fraud_features = synthetic_fraud[features]

    ks_result = statistical_similarity(real_fraud, synthetic_fraud_features, features)
    ks_result.to_csv(PLOTS_DIR.parent / "ks_test_results.csv", index=False)

    plot_feature_distributions(real_fraud, synthetic_fraud_features, features)
    plot_correlation_comparison(real_fraud, synthetic_fraud_features, features)

    tstr_metrics = tstr_evaluation(train_df, test_df, synthetic_fraud, features)
    with open(PLOTS_DIR.parent / "tstr_metrics.json", "w") as f:
        json.dump(tstr_metrics, f, indent=2)

    print("\n[eval] Evaluation of synthetic data completed.")


if __name__ == "__main__":
    main()